<a href="https://colab.research.google.com/github/Elahe-hmh/ML_practice/blob/master/MNIST_(Support_Vector_Machine_classifier_Multiclass).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.datasets import fetch_openml
mnist=fetch_openml('mnist_784', version=1)
X, y = mnist["data"], mnist["target"]

import matplotlib as mpl
import matplotlib.pyplot as plt
some_digit = X[0]
#X[0]:in last note book we saw that it is 5
some_digit_image = some_digit.reshape(28, 28)


import numpy as np
y = y.astype(np.uint8)

X_train, X_test, y_train, y_test = X[:60000], X[60000:], y[:60000], y[60000:]

In [0]:
#only try to identify one digit for example 5
#a binary classifier, capable of distinguishing between just two classes, 5 and not-5
y_train_5 = (y_train == 5)  # True for all 5s, False other digits
y_test_5 = (y_test == 5)


In [3]:
from sklearn.svm import SVC
svm_clf = SVC()
svm_clf.fit(X_train, y_train) # y_train, not y_train_5


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [4]:
svm_clf.predict([some_digit]) 

array([5], dtype=uint8)

In [5]:
# decision_function() method, it returns 10 scoresper instance 
some_digit_scores = svm_clf.decision_function([some_digit])
some_digit_scores
#max score is for 5

array([[ 1.72501977,  2.72809088,  7.2510018 ,  8.3076379 , -0.31087254,
         9.3132482 ,  1.70975103,  2.76765202,  6.23049537,  4.84771048]])

In [6]:
np.argmax(some_digit_scores)

5

In [7]:
svm_clf.classes_

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [8]:
svm_clf.classes_[5]

5

In [9]:
#this code creates a multiclass classifier using the OvR strategy, based on an SVC
from sklearn.multiclass import OneVsRestClassifier
ovr_clf = OneVsRestClassifier(SVC())
ovr_clf.fit(X_train, y_train)
ovr_clf.predict([some_digit])
len(ovr_clf.estimators_)

10

In [11]:
#Training an SGDClassifier is just as easy:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train)
sgd_clf.predict([some_digit])
#This time Scikit-Learn did not have to run OvR or OvO,SGD classifiers can classify into multiple classes

array([3], dtype=uint8)

In [12]:
sgd_clf.decision_function([some_digit])

array([[-31893.03095419, -34419.69069632,  -9530.63950739,
          1823.73154031, -22320.14822878,  -1385.80478895,
        -26188.91070951, -16147.51323997,  -4604.35491274,
        -12050.767298  ]])

In [14]:
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_clf, X_train, y_train, cv=3, scoring="accuracy")

array([0.87365, 0.85835, 0.8689 ])

In [15]:
#Simply scaling the inputs
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.astype(np.float64))
cross_val_score(sgd_clf, X_train_scaled, y_train, cv=3, scoring="accuracy")
#it increases accuracy above 89%

array([0.8983, 0.891 , 0.9018])