In [1]:
import numpy as np


In [2]:
np.random.seed(42)
data=np.random.random((10,3))


In [3]:
data

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643],
       [0.43194502, 0.29122914, 0.61185289],
       [0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041]])

In [4]:
Dict={'age':data[:,0],'rooms':data[:,1],'area':data[:,2]}

In [6]:
Dict['age']

array([0.37454012, 0.59865848, 0.05808361, 0.70807258, 0.83244264,
       0.18340451, 0.43194502, 0.13949386, 0.45606998, 0.51423444])

In [27]:
#data[2:,0]

array([0.05808361, 0.70807258, 0.83244264, 0.18340451, 0.43194502,
       0.13949386, 0.45606998, 0.51423444])

In [31]:
import pandas as pd

In [32]:
test=pd.DataFrame(Dict)

In [33]:
test

age     rooms      area
0  0.374540  0.950714  0.731994
1  0.598658  0.156019  0.155995
2  0.058084  0.866176  0.601115
3  0.708073  0.020584  0.969910
4  0.832443  0.212339  0.181825
5  0.183405  0.304242  0.524756
6  0.431945  0.291229  0.611853
7  0.139494  0.292145  0.366362
8  0.456070  0.785176  0.199674
9  0.514234  0.592415  0.046450